export const data = [
    {
       "id":3,
       "category":"SCIENCEFICTION",
       "title":"BladeRunnerFuture2049.",
       "image":{
          "uri":"https://i.imgur.com/L68FtMA.jpg"
       },
       "rating":4.0
    },
    {
       "id":4,
       "category":"SUPERHEROACTION",
       "title":"CaptainAmericaCivilWar.",
       "image":{
          "uri":"https://i.imgur.com/tAui2H7.jpg"
       },
       "rating":3.5
    },
    {
       "id":5,
       "category":"ROMANCE",
       "title":"BeautyandtheBeast.",
       "image":{
          "uri":"https://i.imgur.com/J5pgFyr.jpg"
       },
       "rating":2.5
    },
    {
       "id":6,
       "category":"DRAMA",
       "title":"ShawshankRedemption.",
       "image":{
          "uri":"https://i.imgur.com/7YGXDbM.jpg"
       },
       "rating":3.0
    }
 ]